C#_projects/Consultorio/Controllers/ConsultaController.cs
using Consultorio.Models;
using Consultorio.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Consultorio.Controllers
{
    //Controllers são responsáveis por trabalhar e buscar dados que serão utilizados para o usuário.
    [Authorize] // SÓ PODE MANIPULAR QUEM TIVER AUTORIZAÇÃO!
    public class ConsultaController : Controller
    {
        IConsultaService service;
        IPacienteService pacienteService;

        public ConsultaController(IConsultaService service, IPacienteService pacienteService)
        {
            this.service = service;
            this.pacienteService = pacienteService;
        }

        public IActionResult Index()
        {
            return View(service.getAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            var pacientes = pacienteService.getAll();
            ViewBag.listaDePacientes = new SelectList(pacientes, "Id", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Consulta consulta)
        {
            var pacientes = pacienteService.getAll();
            ViewBag.listaDePacientes = new SelectList(pacientes, "Id", "Nome");

            if (!ModelState.IsValid) return View(consulta);

            if (service.create(consulta))
                return RedirectToAction(nameof(Index));
            else {
                return View(consulta);
            }
        }  
            

        public IActionResult Read(int? id) // localhost/Paciente/Read/id?
        {
            Consulta consulta = service.get(id);
            return consulta != null ?
                View(consulta) :
                NotFound();
        }

        public IActionResult Update(int? id)
        {
            var pacientes = pacienteService.getAll();
            ViewBag.listaDePacientes = new SelectList(pacientes, "Id", "Nome");
            Consulta consulta = service.get(id);
            return consulta != null ?
                View(consulta) :
                NotFound();
        }

        [HttpPost] 
        [ValidateAntiForgeryToken]
        public IActionResult Update(Consulta consulta)
        {
            var pacientes = pacienteService.getAll();
            ViewBag.listaDePacientes = new SelectList(pacientes, "Id", "Nome");
            if (!ModelState.IsValid) return View(consulta);

            if (service.update(consulta)) //// PacienteStaticService.Create(paciente)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(consulta);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (service.delete(id)) //// PacienteStaticService.Create(paciente)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

C#_projects/Consultorio/Controllers/PacienteController.cs
using Consultorio.Models;
using Consultorio.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Consultorio.Controllers
{
    //Controllers são responsáveis por trabalhar e buscar dados que serão utilizados para o usuário.
    public class PacienteController : Controller
    {
        IPacienteService service;

        public PacienteController(IPacienteService service)
        {
            this.service = service;
        }

        public IActionResult Index(string busca, bool ordenar = false)
        {
            ViewBag.ordenar = ordenar;
            Random r = new Random();

            return View(service.getAll(busca,ordenar));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Paciente paciente)
        {
            if (!ModelState.IsValid) return View(paciente);

            return service.create(paciente) ?
                RedirectToAction(nameof(Index)) :
                View(paciente);
        }  
            

        public IActionResult Read(int? id) // localhost/Paciente/Read/id?
        {
            Paciente paciente = service.get(id);
            return paciente != null ?
                View(paciente) :
                NotFound();
        }

        public IActionResult Update(int? id)
        {
            Paciente paciente = service.get(id);
            return paciente != null ?
                View(paciente) :
                NotFound();
        }

        [HttpPost] 
        [ValidateAntiForgeryToken]
        public IActionResult Update(Paciente paciente)
        {
            if(!ModelState.IsValid) return View(paciente);

            if (service.update(paciente)) //// PacienteStaticService.Create(paciente)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(paciente);
            }
        }

        public IActionResult Delete(int? id)
        {
            if (service.delete(id)) //// PacienteStaticService.Create(paciente)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

C#_projects/Consultorio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consultorio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consultorio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Paciente</a>
                        </li>
                        <partial name="_LoggedInMenu" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Consultorio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

C#_projects/Consultorio/Views/Shared/_LoggedInMenu.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Consulta" asp-action="Index">Consulta</a>
    </li>
}